Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,24 +1,39 @@
-name: CICD-Actions
+name: CI/CD
 
-on: 
+on:
   push:
-    branches: [master]
+    branches:
+      - master
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
 
-      - name: Deploy to server
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          script: |
-            cd $GITHUB_WORKSPACE  # Используем переменную окружения GITHUB_WORKSPACE
-            git pull https://:${{ secrets.GITHUB_TOKEN }}@github.com/dil0rd/mysite.git master
-            # Теперь выполните перезапуск службы nginx на самом сервере, а не внутри Docker-контейнера
-            sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart nginx'
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Run checks
+      run: |
+        # Проверки вашего условия
+        # Примеры:
+        # 1. Проверка на отсутствие файлов с расширениями css, js
+        if [ -n "$(find . -name '*.css' -o -name '*.js')" ]; then
+          echo "Error: CSS or JS files found"
+          exit 1
+        fi
+
+        # 2. Проверка размера файлов (пример для файлов > 1MB)
+        find . -type f -size +1M -exec echo "Error: File {} exceeds 1MB" \; && exit 1
+
+        # 3. Другие проверки...
+
+    - name: Deploy to server
+      if: success()
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.SSH_HOST }}
+        username: ${{ secrets.SSH_USERNAME }}
+        password: ${{ secrets.SSH_PASSWORD }}
+        script: |
+          # Ваш скрипт развертывания на сервере
